name: Build Electron App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'  # Кэширование зависимостей

    - name: Generate lock file
      run: npm install --package-lock-only

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Build Electron
      env:
        NPM_CONFIG_USER_AGENT: npm
      run: npm run electron:build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: dist/*.exe
