name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g npm@latest
        
    - name: Build app
      run: npm run build

    - name: Build Electron (force npm)
      run: npm run electron:build -- --config.npmClient=npm --config.npmRebuild=false

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: |
          dist/*.exe
          dist/*.blockmap
