name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4  # Также обновите checkout

    - name: Use Node.js
      uses: actions/setup-node@v4  # И setup-node
      with:
        node-version: '20'  # Рекомендую Node.js 20 (LTS)

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Build Electron app for Windows
      run: npm run electron:build -- -w

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4  # 🔥 Ключевое изменение!
      with:
        name: MyApp-Windows
        path: |
          release/*.exe
          release/*.blockmap
