name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    # Добавьте этот шаг сразу после checkout
    - name: Install npm explicitly
      run: npm install -g npm@latest

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Рекомендуемая LTS версия

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Build Electron app for Windows
      run: npm run electron:build -- -w

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-Windows
        path: |
          release/*.exe
          release/*.blockmap
